package com.bpd.pojos.sql;
// Generated May 12, 2011 2:44:00 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * AsOfEmployee generated by hbm2java
 */
public class AsOfEmployee  implements java.io.Serializable {


     private int empleado;
     private String nombre;
     private String firstName;
     private String firstMiddleName;
     private String lastName;
     private String alias;
     private String emplId;
     private String emplDesc;
     private String unidad;
     private String departamento;
     private String puesto;
     private String cargo;
     private Date hireDate;
     private Date recoDateIni;
     private Date recoDateFin;
     private Date statusChangeDate;
     private String employmentTypeCode;
     private char empStatusCode;
     private String payGradeCode;
     private BigDecimal pdSalaryAmt;
     private BigDecimal annualSalaryAmt;
     private String centro;
     private String locCode;
     private String locName;
     private String phone1AreaCityCode;
     private String phone1Nbr;
     private String phone1ExtensionNbr;
     private String phone2AreaCityCode;
     private String phone2Nbr;
     private String phone2ExtensionNbr;
     private String phone3AreaCityCode;
     private String phone3Nbr;
     private String phone3ExtensionNbr;
     private Date salaryChangeDate;
     private String salaryChangeTypeCode;
     private int mgrEmpId;
     private String mgrName;
     private String mgrPhone;
     private String depositAcctNbr;
     private String polizaId;
     private String individualId;
     private char sexCode;
     private Date birthDate;
     private Date deathDate;
     private String nroBeeper;
     private String nroCodeflota;
     private String nroCelular;
     private String serialArmaDeFuego;
     private String tipoArmaDeFuego;
     private String addr1Line1;
     private String addr1Line2;
     private String addr1Line3;
     private String addr1StreetOrPob1;
     private String addr1StreetOrPob2;
     private String addr1CityName;
     private String addr1CountrySubEntityCode;
     private String addr1PostalCode;
     private String addr1CountryCode;
     private String bloodTypeCode;
     private Character bloodDonorInd;
     private String height;
     private String weight;
     private String nationalId1;
     private String lastActionCode;
     private char empInfoSourceCode;
     private String activeReasonCode;
     private String empPhoto;
     private String rutaPhoto;
     private Date asOfDate;
     private String puestoSupCom;
     private String puestoSupAdm;
     private Long idCumpleano;

    public AsOfEmployee() {
    }

	
    public AsOfEmployee(int empleado, String nombre, String firstName, String firstMiddleName, String lastName, String alias, String emplId, String emplDesc, String unidad, String departamento, String puesto, String cargo, Date hireDate, Date recoDateIni, Date statusChangeDate, String employmentTypeCode, char empStatusCode, String payGradeCode, BigDecimal pdSalaryAmt, BigDecimal annualSalaryAmt, String centro, String locCode, Date salaryChangeDate, String salaryChangeTypeCode, int mgrEmpId, String mgrName, String mgrPhone, String depositAcctNbr, String polizaId, String individualId, char sexCode, Date birthDate, String addr1Line1, String addr1Line2, String addr1Line3, String addr1StreetOrPob1, String addr1StreetOrPob2, String addr1CityName, String addr1CountrySubEntityCode, String addr1PostalCode, String addr1CountryCode, String bloodTypeCode, String nationalId1, String lastActionCode, char empInfoSourceCode, String activeReasonCode, Date asOfDate) {
        this.empleado = empleado;
        this.nombre = nombre;
        this.firstName = firstName;
        this.firstMiddleName = firstMiddleName;
        this.lastName = lastName;
        this.alias = alias;
        this.emplId = emplId;
        this.emplDesc = emplDesc;
        this.unidad = unidad;
        this.departamento = departamento;
        this.puesto = puesto;
        this.cargo = cargo;
        this.hireDate = hireDate;
        this.recoDateIni = recoDateIni;
        this.statusChangeDate = statusChangeDate;
        this.employmentTypeCode = employmentTypeCode;
        this.empStatusCode = empStatusCode;
        this.payGradeCode = payGradeCode;
        this.pdSalaryAmt = pdSalaryAmt;
        this.annualSalaryAmt = annualSalaryAmt;
        this.centro = centro;
        this.locCode = locCode;
        this.salaryChangeDate = salaryChangeDate;
        this.salaryChangeTypeCode = salaryChangeTypeCode;
        this.mgrEmpId = mgrEmpId;
        this.mgrName = mgrName;
        this.mgrPhone = mgrPhone;
        this.depositAcctNbr = depositAcctNbr;
        this.polizaId = polizaId;
        this.individualId = individualId;
        this.sexCode = sexCode;
        this.birthDate = birthDate;
        this.addr1Line1 = addr1Line1;
        this.addr1Line2 = addr1Line2;
        this.addr1Line3 = addr1Line3;
        this.addr1StreetOrPob1 = addr1StreetOrPob1;
        this.addr1StreetOrPob2 = addr1StreetOrPob2;
        this.addr1CityName = addr1CityName;
        this.addr1CountrySubEntityCode = addr1CountrySubEntityCode;
        this.addr1PostalCode = addr1PostalCode;
        this.addr1CountryCode = addr1CountryCode;
        this.bloodTypeCode = bloodTypeCode;
        this.nationalId1 = nationalId1;
        this.lastActionCode = lastActionCode;
        this.empInfoSourceCode = empInfoSourceCode;
        this.activeReasonCode = activeReasonCode;
        this.asOfDate = asOfDate;
    }
    public AsOfEmployee(int empleado, String nombre, String firstName, String firstMiddleName, String lastName, String alias, String emplId, String emplDesc, String unidad, String departamento, String puesto, String cargo, Date hireDate, Date recoDateIni, Date recoDateFin, Date statusChangeDate, String employmentTypeCode, char empStatusCode, String payGradeCode, BigDecimal pdSalaryAmt, BigDecimal annualSalaryAmt, String centro, String locCode, String locName, String phone1AreaCityCode, String phone1Nbr, String phone1ExtensionNbr, String phone2AreaCityCode, String phone2Nbr, String phone2ExtensionNbr, String phone3AreaCityCode, String phone3Nbr, String phone3ExtensionNbr, Date salaryChangeDate, String salaryChangeTypeCode, int mgrEmpId, String mgrName, String mgrPhone, String depositAcctNbr, String polizaId, String individualId, char sexCode, Date birthDate, Date deathDate, String nroBeeper, String nroCodeflota, String nroCelular, String serialArmaDeFuego, String tipoArmaDeFuego, String addr1Line1, String addr1Line2, String addr1Line3, String addr1StreetOrPob1, String addr1StreetOrPob2, String addr1CityName, String addr1CountrySubEntityCode, String addr1PostalCode, String addr1CountryCode, String bloodTypeCode, Character bloodDonorInd, String height, String weight, String nationalId1, String lastActionCode, char empInfoSourceCode, String activeReasonCode, String empPhoto, String rutaPhoto, Date asOfDate, String puestoSupCom, String puestoSupAdm, Long idCumpleano) {
       this.empleado = empleado;
       this.nombre = nombre;
       this.firstName = firstName;
       this.firstMiddleName = firstMiddleName;
       this.lastName = lastName;
       this.alias = alias;
       this.emplId = emplId;
       this.emplDesc = emplDesc;
       this.unidad = unidad;
       this.departamento = departamento;
       this.puesto = puesto;
       this.cargo = cargo;
       this.hireDate = hireDate;
       this.recoDateIni = recoDateIni;
       this.recoDateFin = recoDateFin;
       this.statusChangeDate = statusChangeDate;
       this.employmentTypeCode = employmentTypeCode;
       this.empStatusCode = empStatusCode;
       this.payGradeCode = payGradeCode;
       this.pdSalaryAmt = pdSalaryAmt;
       this.annualSalaryAmt = annualSalaryAmt;
       this.centro = centro;
       this.locCode = locCode;
       this.locName = locName;
       this.phone1AreaCityCode = phone1AreaCityCode;
       this.phone1Nbr = phone1Nbr;
       this.phone1ExtensionNbr = phone1ExtensionNbr;
       this.phone2AreaCityCode = phone2AreaCityCode;
       this.phone2Nbr = phone2Nbr;
       this.phone2ExtensionNbr = phone2ExtensionNbr;
       this.phone3AreaCityCode = phone3AreaCityCode;
       this.phone3Nbr = phone3Nbr;
       this.phone3ExtensionNbr = phone3ExtensionNbr;
       this.salaryChangeDate = salaryChangeDate;
       this.salaryChangeTypeCode = salaryChangeTypeCode;
       this.mgrEmpId = mgrEmpId;
       this.mgrName = mgrName;
       this.mgrPhone = mgrPhone;
       this.depositAcctNbr = depositAcctNbr;
       this.polizaId = polizaId;
       this.individualId = individualId;
       this.sexCode = sexCode;
       this.birthDate = birthDate;
       this.deathDate = deathDate;
       this.nroBeeper = nroBeeper;
       this.nroCodeflota = nroCodeflota;
       this.nroCelular = nroCelular;
       this.serialArmaDeFuego = serialArmaDeFuego;
       this.tipoArmaDeFuego = tipoArmaDeFuego;
       this.addr1Line1 = addr1Line1;
       this.addr1Line2 = addr1Line2;
       this.addr1Line3 = addr1Line3;
       this.addr1StreetOrPob1 = addr1StreetOrPob1;
       this.addr1StreetOrPob2 = addr1StreetOrPob2;
       this.addr1CityName = addr1CityName;
       this.addr1CountrySubEntityCode = addr1CountrySubEntityCode;
       this.addr1PostalCode = addr1PostalCode;
       this.addr1CountryCode = addr1CountryCode;
       this.bloodTypeCode = bloodTypeCode;
       this.bloodDonorInd = bloodDonorInd;
       this.height = height;
       this.weight = weight;
       this.nationalId1 = nationalId1;
       this.lastActionCode = lastActionCode;
       this.empInfoSourceCode = empInfoSourceCode;
       this.activeReasonCode = activeReasonCode;
       this.empPhoto = empPhoto;
       this.rutaPhoto = rutaPhoto;
       this.asOfDate = asOfDate;
       this.puestoSupCom = puestoSupCom;
       this.puestoSupAdm = puestoSupAdm;
       this.idCumpleano = idCumpleano;
    }
   
    public int getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(int empleado) {
        this.empleado = empleado;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getFirstMiddleName() {
        return this.firstMiddleName;
    }
    
    public void setFirstMiddleName(String firstMiddleName) {
        this.firstMiddleName = firstMiddleName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getAlias() {
        return this.alias;
    }
    
    public void setAlias(String alias) {
        this.alias = alias;
    }
    public String getEmplId() {
        return this.emplId;
    }
    
    public void setEmplId(String emplId) {
        this.emplId = emplId;
    }
    public String getEmplDesc() {
        return this.emplDesc;
    }
    
    public void setEmplDesc(String emplDesc) {
        this.emplDesc = emplDesc;
    }
    public String getUnidad() {
        return this.unidad;
    }
    
    public void setUnidad(String unidad) {
        this.unidad = unidad;
    }
    public String getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(String departamento) {
        this.departamento = departamento;
    }
    public String getPuesto() {
        return this.puesto;
    }
    
    public void setPuesto(String puesto) {
        this.puesto = puesto;
    }
    public String getCargo() {
        return this.cargo;
    }
    
    public void setCargo(String cargo) {
        this.cargo = cargo;
    }
    public Date getHireDate() {
        return this.hireDate;
    }
    
    public void setHireDate(Date hireDate) {
        this.hireDate = hireDate;
    }
    public Date getRecoDateIni() {
        return this.recoDateIni;
    }
    
    public void setRecoDateIni(Date recoDateIni) {
        this.recoDateIni = recoDateIni;
    }
    public Date getRecoDateFin() {
        return this.recoDateFin;
    }
    
    public void setRecoDateFin(Date recoDateFin) {
        this.recoDateFin = recoDateFin;
    }
    public Date getStatusChangeDate() {
        return this.statusChangeDate;
    }
    
    public void setStatusChangeDate(Date statusChangeDate) {
        this.statusChangeDate = statusChangeDate;
    }
    public String getEmploymentTypeCode() {
        return this.employmentTypeCode;
    }
    
    public void setEmploymentTypeCode(String employmentTypeCode) {
        this.employmentTypeCode = employmentTypeCode;
    }
    public char getEmpStatusCode() {
        return this.empStatusCode;
    }
    
    public void setEmpStatusCode(char empStatusCode) {
        this.empStatusCode = empStatusCode;
    }
    public String getPayGradeCode() {
        return this.payGradeCode;
    }
    
    public void setPayGradeCode(String payGradeCode) {
        this.payGradeCode = payGradeCode;
    }
    public BigDecimal getPdSalaryAmt() {
        return this.pdSalaryAmt;
    }
    
    public void setPdSalaryAmt(BigDecimal pdSalaryAmt) {
        this.pdSalaryAmt = pdSalaryAmt;
    }
    public BigDecimal getAnnualSalaryAmt() {
        return this.annualSalaryAmt;
    }
    
    public void setAnnualSalaryAmt(BigDecimal annualSalaryAmt) {
        this.annualSalaryAmt = annualSalaryAmt;
    }
    public String getCentro() {
        return this.centro;
    }
    
    public void setCentro(String centro) {
        this.centro = centro;
    }
    public String getLocCode() {
        return this.locCode;
    }
    
    public void setLocCode(String locCode) {
        this.locCode = locCode;
    }
    public String getLocName() {
        return this.locName;
    }
    
    public void setLocName(String locName) {
        this.locName = locName;
    }
    public String getPhone1AreaCityCode() {
        return this.phone1AreaCityCode;
    }
    
    public void setPhone1AreaCityCode(String phone1AreaCityCode) {
        this.phone1AreaCityCode = phone1AreaCityCode;
    }
    public String getPhone1Nbr() {
        return this.phone1Nbr;
    }
    
    public void setPhone1Nbr(String phone1Nbr) {
        this.phone1Nbr = phone1Nbr;
    }
    public String getPhone1ExtensionNbr() {
        return this.phone1ExtensionNbr;
    }
    
    public void setPhone1ExtensionNbr(String phone1ExtensionNbr) {
        this.phone1ExtensionNbr = phone1ExtensionNbr;
    }
    public String getPhone2AreaCityCode() {
        return this.phone2AreaCityCode;
    }
    
    public void setPhone2AreaCityCode(String phone2AreaCityCode) {
        this.phone2AreaCityCode = phone2AreaCityCode;
    }
    public String getPhone2Nbr() {
        return this.phone2Nbr;
    }
    
    public void setPhone2Nbr(String phone2Nbr) {
        this.phone2Nbr = phone2Nbr;
    }
    public String getPhone2ExtensionNbr() {
        return this.phone2ExtensionNbr;
    }
    
    public void setPhone2ExtensionNbr(String phone2ExtensionNbr) {
        this.phone2ExtensionNbr = phone2ExtensionNbr;
    }
    public String getPhone3AreaCityCode() {
        return this.phone3AreaCityCode;
    }
    
    public void setPhone3AreaCityCode(String phone3AreaCityCode) {
        this.phone3AreaCityCode = phone3AreaCityCode;
    }
    public String getPhone3Nbr() {
        return this.phone3Nbr;
    }
    
    public void setPhone3Nbr(String phone3Nbr) {
        this.phone3Nbr = phone3Nbr;
    }
    public String getPhone3ExtensionNbr() {
        return this.phone3ExtensionNbr;
    }
    
    public void setPhone3ExtensionNbr(String phone3ExtensionNbr) {
        this.phone3ExtensionNbr = phone3ExtensionNbr;
    }
    public Date getSalaryChangeDate() {
        return this.salaryChangeDate;
    }
    
    public void setSalaryChangeDate(Date salaryChangeDate) {
        this.salaryChangeDate = salaryChangeDate;
    }
    public String getSalaryChangeTypeCode() {
        return this.salaryChangeTypeCode;
    }
    
    public void setSalaryChangeTypeCode(String salaryChangeTypeCode) {
        this.salaryChangeTypeCode = salaryChangeTypeCode;
    }
    public int getMgrEmpId() {
        return this.mgrEmpId;
    }
    
    public void setMgrEmpId(int mgrEmpId) {
        this.mgrEmpId = mgrEmpId;
    }
    public String getMgrName() {
        return this.mgrName;
    }
    
    public void setMgrName(String mgrName) {
        this.mgrName = mgrName;
    }
    public String getMgrPhone() {
        return this.mgrPhone;
    }
    
    public void setMgrPhone(String mgrPhone) {
        this.mgrPhone = mgrPhone;
    }
    public String getDepositAcctNbr() {
        return this.depositAcctNbr;
    }
    
    public void setDepositAcctNbr(String depositAcctNbr) {
        this.depositAcctNbr = depositAcctNbr;
    }
    public String getPolizaId() {
        return this.polizaId;
    }
    
    public void setPolizaId(String polizaId) {
        this.polizaId = polizaId;
    }
    public String getIndividualId() {
        return this.individualId;
    }
    
    public void setIndividualId(String individualId) {
        this.individualId = individualId;
    }
    public char getSexCode() {
        return this.sexCode;
    }
    
    public void setSexCode(char sexCode) {
        this.sexCode = sexCode;
    }
    public Date getBirthDate() {
        return this.birthDate;
    }
    
    public void setBirthDate(Date birthDate) {
        this.birthDate = birthDate;
    }
    public Date getDeathDate() {
        return this.deathDate;
    }
    
    public void setDeathDate(Date deathDate) {
        this.deathDate = deathDate;
    }
    public String getNroBeeper() {
        return this.nroBeeper;
    }
    
    public void setNroBeeper(String nroBeeper) {
        this.nroBeeper = nroBeeper;
    }
    public String getNroCodeflota() {
        return this.nroCodeflota;
    }
    
    public void setNroCodeflota(String nroCodeflota) {
        this.nroCodeflota = nroCodeflota;
    }
    public String getNroCelular() {
        return this.nroCelular;
    }
    
    public void setNroCelular(String nroCelular) {
        this.nroCelular = nroCelular;
    }
    public String getSerialArmaDeFuego() {
        return this.serialArmaDeFuego;
    }
    
    public void setSerialArmaDeFuego(String serialArmaDeFuego) {
        this.serialArmaDeFuego = serialArmaDeFuego;
    }
    public String getTipoArmaDeFuego() {
        return this.tipoArmaDeFuego;
    }
    
    public void setTipoArmaDeFuego(String tipoArmaDeFuego) {
        this.tipoArmaDeFuego = tipoArmaDeFuego;
    }
    public String getAddr1Line1() {
        return this.addr1Line1;
    }
    
    public void setAddr1Line1(String addr1Line1) {
        this.addr1Line1 = addr1Line1;
    }
    public String getAddr1Line2() {
        return this.addr1Line2;
    }
    
    public void setAddr1Line2(String addr1Line2) {
        this.addr1Line2 = addr1Line2;
    }
    public String getAddr1Line3() {
        return this.addr1Line3;
    }
    
    public void setAddr1Line3(String addr1Line3) {
        this.addr1Line3 = addr1Line3;
    }
    public String getAddr1StreetOrPob1() {
        return this.addr1StreetOrPob1;
    }
    
    public void setAddr1StreetOrPob1(String addr1StreetOrPob1) {
        this.addr1StreetOrPob1 = addr1StreetOrPob1;
    }
    public String getAddr1StreetOrPob2() {
        return this.addr1StreetOrPob2;
    }
    
    public void setAddr1StreetOrPob2(String addr1StreetOrPob2) {
        this.addr1StreetOrPob2 = addr1StreetOrPob2;
    }
    public String getAddr1CityName() {
        return this.addr1CityName;
    }
    
    public void setAddr1CityName(String addr1CityName) {
        this.addr1CityName = addr1CityName;
    }
    public String getAddr1CountrySubEntityCode() {
        return this.addr1CountrySubEntityCode;
    }
    
    public void setAddr1CountrySubEntityCode(String addr1CountrySubEntityCode) {
        this.addr1CountrySubEntityCode = addr1CountrySubEntityCode;
    }
    public String getAddr1PostalCode() {
        return this.addr1PostalCode;
    }
    
    public void setAddr1PostalCode(String addr1PostalCode) {
        this.addr1PostalCode = addr1PostalCode;
    }
    public String getAddr1CountryCode() {
        return this.addr1CountryCode;
    }
    
    public void setAddr1CountryCode(String addr1CountryCode) {
        this.addr1CountryCode = addr1CountryCode;
    }
    public String getBloodTypeCode() {
        return this.bloodTypeCode;
    }
    
    public void setBloodTypeCode(String bloodTypeCode) {
        this.bloodTypeCode = bloodTypeCode;
    }
    public Character getBloodDonorInd() {
        return this.bloodDonorInd;
    }
    
    public void setBloodDonorInd(Character bloodDonorInd) {
        this.bloodDonorInd = bloodDonorInd;
    }
    public String getHeight() {
        return this.height;
    }
    
    public void setHeight(String height) {
        this.height = height;
    }
    public String getWeight() {
        return this.weight;
    }
    
    public void setWeight(String weight) {
        this.weight = weight;
    }
    public String getNationalId1() {
        return this.nationalId1;
    }
    
    public void setNationalId1(String nationalId1) {
        this.nationalId1 = nationalId1;
    }
    public String getLastActionCode() {
        return this.lastActionCode;
    }
    
    public void setLastActionCode(String lastActionCode) {
        this.lastActionCode = lastActionCode;
    }
    public char getEmpInfoSourceCode() {
        return this.empInfoSourceCode;
    }
    
    public void setEmpInfoSourceCode(char empInfoSourceCode) {
        this.empInfoSourceCode = empInfoSourceCode;
    }
    public String getActiveReasonCode() {
        return this.activeReasonCode;
    }
    
    public void setActiveReasonCode(String activeReasonCode) {
        this.activeReasonCode = activeReasonCode;
    }
    public String getEmpPhoto() {
        return this.empPhoto;
    }
    
    public void setEmpPhoto(String empPhoto) {
        this.empPhoto = empPhoto;
    }
    public String getRutaPhoto() {
        return this.rutaPhoto;
    }
    
    public void setRutaPhoto(String rutaPhoto) {
        this.rutaPhoto = rutaPhoto;
    }
    public Date getAsOfDate() {
        return this.asOfDate;
    }
    
    public void setAsOfDate(Date asOfDate) {
        this.asOfDate = asOfDate;
    }
    public String getPuestoSupCom() {
        return this.puestoSupCom;
    }
    
    public void setPuestoSupCom(String puestoSupCom) {
        this.puestoSupCom = puestoSupCom;
    }
    public String getPuestoSupAdm() {
        return this.puestoSupAdm;
    }
    
    public void setPuestoSupAdm(String puestoSupAdm) {
        this.puestoSupAdm = puestoSupAdm;
    }
    public Long getIdCumpleano() {
        return this.idCumpleano;
    }
    
    public void setIdCumpleano(Long idCumpleano) {
        this.idCumpleano = idCumpleano;
    }




}


