package com.bpd.pojos;
// Generated May 9, 2011 3:23:30 PM by Hibernate Tools 3.2.1.GA



/**
 * VwSsMaEmpleadosActivos generated by hbm2java
 */
public class VwSsMaEmpleadosActivos  implements java.io.Serializable {


     private Integer id;
     private Integer codigoEmpleado;
     private String nombreEmpleado;
     private String unidad;
     private String departamento;
     private String cargo;
     private String puesto;
     private Integer mgrEmpId;
     private String codigoSupervisorOriginal;
     private String emplId;
     private String emplDesc;
     private String empStatusCode;
     private String firstName;
     private String firstMiddleName;
     private String lastName;
     private String alias;
     private String hireDate;
     private String employmentTypeCode;
     private String payGradeCode;
     private String centro;
     private String locCode;
     private String phone1AreaCityCode;
     private String phone1Nbr;
     private String phone1ExtensionNbr;
     private String depositAcctNbr;
     private String polizaId;
     private String individualId;
     private String sexCode;
     private String birthDate;
     private String bloodTypeCode;
     private String bloodDonorInd;
     private String height;
     private String weight;
     private String nationalId1;
     private String empPhoto;
     private String rutaPhoto;
     private String admRrhh;

    public VwSsMaEmpleadosActivos() {
    }

    public VwSsMaEmpleadosActivos(Integer codigoEmpleado, String nombreEmpleado, String unidad, String departamento, String cargo, String puesto, Integer mgrEmpId, String codigoSupervisorOriginal, String emplId, String emplDesc, String empStatusCode, String firstName, String firstMiddleName, String lastName, String alias, String hireDate, String employmentTypeCode, String payGradeCode, String centro, String locCode, String phone1AreaCityCode, String phone1Nbr, String phone1ExtensionNbr, String depositAcctNbr, String polizaId, String individualId, String sexCode, String birthDate, String bloodTypeCode, String bloodDonorInd, String height, String weight, String nationalId1, String empPhoto, String rutaPhoto, String admRrhh) {
       this.codigoEmpleado = codigoEmpleado;
       this.nombreEmpleado = nombreEmpleado;
       this.unidad = unidad;
       this.departamento = departamento;
       this.cargo = cargo;
       this.puesto = puesto;
       this.mgrEmpId = mgrEmpId;
       this.codigoSupervisorOriginal = codigoSupervisorOriginal;
       this.emplId = emplId;
       this.emplDesc = emplDesc;
       this.empStatusCode = empStatusCode;
       this.firstName = firstName;
       this.firstMiddleName = firstMiddleName;
       this.lastName = lastName;
       this.alias = alias;
       this.hireDate = hireDate;
       this.employmentTypeCode = employmentTypeCode;
       this.payGradeCode = payGradeCode;
       this.centro = centro;
       this.locCode = locCode;
       this.phone1AreaCityCode = phone1AreaCityCode;
       this.phone1Nbr = phone1Nbr;
       this.phone1ExtensionNbr = phone1ExtensionNbr;
       this.depositAcctNbr = depositAcctNbr;
       this.polizaId = polizaId;
       this.individualId = individualId;
       this.sexCode = sexCode;
       this.birthDate = birthDate;
       this.bloodTypeCode = bloodTypeCode;
       this.bloodDonorInd = bloodDonorInd;
       this.height = height;
       this.weight = weight;
       this.nationalId1 = nationalId1;
       this.empPhoto = empPhoto;
       this.rutaPhoto = rutaPhoto;
       this.admRrhh = admRrhh;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getCodigoEmpleado() {
        return this.codigoEmpleado;
    }
    
    public void setCodigoEmpleado(Integer codigoEmpleado) {
        this.codigoEmpleado = codigoEmpleado;
    }
    public String getNombreEmpleado() {
        return this.nombreEmpleado;
    }
    
    public void setNombreEmpleado(String nombreEmpleado) {
        this.nombreEmpleado = nombreEmpleado;
    }
    public String getUnidad() {
        return this.unidad;
    }
    
    public void setUnidad(String unidad) {
        this.unidad = unidad;
    }
    public String getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(String departamento) {
        this.departamento = departamento;
    }
    public String getCargo() {
        return this.cargo;
    }
    
    public void setCargo(String cargo) {
        this.cargo = cargo;
    }
    public String getPuesto() {
        return this.puesto;
    }
    
    public void setPuesto(String puesto) {
        this.puesto = puesto;
    }
    public Integer getMgrEmpId() {
        return this.mgrEmpId;
    }
    
    public void setMgrEmpId(Integer mgrEmpId) {
        this.mgrEmpId = mgrEmpId;
    }
    public String getCodigoSupervisorOriginal() {
        return this.codigoSupervisorOriginal;
    }
    
    public void setCodigoSupervisorOriginal(String codigoSupervisorOriginal) {
        this.codigoSupervisorOriginal = codigoSupervisorOriginal;
    }
    public String getEmplId() {
        return this.emplId;
    }
    
    public void setEmplId(String emplId) {
        this.emplId = emplId;
    }
    public String getEmplDesc() {
        return this.emplDesc;
    }
    
    public void setEmplDesc(String emplDesc) {
        this.emplDesc = emplDesc;
    }
    public String getEmpStatusCode() {
        return this.empStatusCode;
    }
    
    public void setEmpStatusCode(String empStatusCode) {
        this.empStatusCode = empStatusCode;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getFirstMiddleName() {
        return this.firstMiddleName;
    }
    
    public void setFirstMiddleName(String firstMiddleName) {
        this.firstMiddleName = firstMiddleName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getAlias() {
        return this.alias;
    }
    
    public void setAlias(String alias) {
        this.alias = alias;
    }
    public String getHireDate() {
        return this.hireDate;
    }
    
    public void setHireDate(String hireDate) {
        this.hireDate = hireDate;
    }
    public String getEmploymentTypeCode() {
        return this.employmentTypeCode;
    }
    
    public void setEmploymentTypeCode(String employmentTypeCode) {
        this.employmentTypeCode = employmentTypeCode;
    }
    public String getPayGradeCode() {
        return this.payGradeCode;
    }
    
    public void setPayGradeCode(String payGradeCode) {
        this.payGradeCode = payGradeCode;
    }
    public String getCentro() {
        return this.centro;
    }
    
    public void setCentro(String centro) {
        this.centro = centro;
    }
    public String getLocCode() {
        return this.locCode;
    }
    
    public void setLocCode(String locCode) {
        this.locCode = locCode;
    }
    public String getPhone1AreaCityCode() {
        return this.phone1AreaCityCode;
    }
    
    public void setPhone1AreaCityCode(String phone1AreaCityCode) {
        this.phone1AreaCityCode = phone1AreaCityCode;
    }
    public String getPhone1Nbr() {
        return this.phone1Nbr;
    }
    
    public void setPhone1Nbr(String phone1Nbr) {
        this.phone1Nbr = phone1Nbr;
    }
    public String getPhone1ExtensionNbr() {
        return this.phone1ExtensionNbr;
    }
    
    public void setPhone1ExtensionNbr(String phone1ExtensionNbr) {
        this.phone1ExtensionNbr = phone1ExtensionNbr;
    }
    public String getDepositAcctNbr() {
        return this.depositAcctNbr;
    }
    
    public void setDepositAcctNbr(String depositAcctNbr) {
        this.depositAcctNbr = depositAcctNbr;
    }
    public String getPolizaId() {
        return this.polizaId;
    }
    
    public void setPolizaId(String polizaId) {
        this.polizaId = polizaId;
    }
    public String getIndividualId() {
        return this.individualId;
    }
    
    public void setIndividualId(String individualId) {
        this.individualId = individualId;
    }
    public String getSexCode() {
        return this.sexCode;
    }
    
    public void setSexCode(String sexCode) {
        this.sexCode = sexCode;
    }
    public String getBirthDate() {
        return this.birthDate;
    }
    
    public void setBirthDate(String birthDate) {
        this.birthDate = birthDate;
    }
    public String getBloodTypeCode() {
        return this.bloodTypeCode;
    }
    
    public void setBloodTypeCode(String bloodTypeCode) {
        this.bloodTypeCode = bloodTypeCode;
    }
    public String getBloodDonorInd() {
        return this.bloodDonorInd;
    }
    
    public void setBloodDonorInd(String bloodDonorInd) {
        this.bloodDonorInd = bloodDonorInd;
    }
    public String getHeight() {
        return this.height;
    }
    
    public void setHeight(String height) {
        this.height = height;
    }
    public String getWeight() {
        return this.weight;
    }
    
    public void setWeight(String weight) {
        this.weight = weight;
    }
    public String getNationalId1() {
        return this.nationalId1;
    }
    
    public void setNationalId1(String nationalId1) {
        this.nationalId1 = nationalId1;
    }
    public String getEmpPhoto() {
        return this.empPhoto;
    }
    
    public void setEmpPhoto(String empPhoto) {
        this.empPhoto = empPhoto;
    }
    public String getRutaPhoto() {
        return this.rutaPhoto;
    }
    
    public void setRutaPhoto(String rutaPhoto) {
        this.rutaPhoto = rutaPhoto;
    }
    public String getAdmRrhh() {
        return this.admRrhh;
    }
    
    public void setAdmRrhh(String admRrhh) {
        this.admRrhh = admRrhh;
    }




}


