<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Untitled Document</title>
</head>

<body>
<span class="Apple-style-span" style="color: rgb(0, 0, 0); font-family: verdana, arial, helvetica, sans-serif; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: 2; text-align: -webkit-auto; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-decorations-in-effect: none; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); font-size: small; ">
<h1 class="sans-serif" style="margin-top: 2px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; font-size: 18px; ">
  <div style="color: rgb(204, 102, 0); ">Customer Reviews</div>
  <div style="font-size: 15px; text-decoration: underline; "><a href="http://www.amazon.com/TAG-Heuer-CAH1110-BA0850-Formula-Chronograph/dp/B0019FP47E/ref=cm_cr_pr_product_top" style="font-family: verdana, arial, helvetica, sans-serif; color: rgb(0, 75, 145); ">TAG Heuer Men's CAH1110.BA0850 Formula 1 Chronograph Watch</a></div>
</h1>
<br>
<table id="productSummary" border="0" cellspacing="0" cellpadding="0" width="100%">
  <tbody>
    <tr>
      <td width="160" style="font-family: verdana, arial, helvetica, sans-serif; font-size: small; border-top-width: 0px; border-right-width: 0px; border-bottom-width: 0px; border-left-width: 0px; border-style: initial; border-color: initial; "><div style="width: 160px; ">
        <div class="tiny" style="font-family: verdana, arial, helvetica, sans-serif; font-size: x-small; display: block; text-align: center; padding-bottom: 5px; "><strong>25 Reviews</strong></div>
        <table border="0" cellspacing="1" cellpadding="0" align="left">
          <tbody>
            <tr>
              <td align="left" class="tiny" style="font-family: verdana, arial, helvetica, sans-serif; font-size: x-small; border-top-width: 0px; border-right-width: 0px; border-bottom-width: 0px; border-left-width: 0px; border-style: initial; border-color: initial; padding-right: 0.5em; padding-bottom: 1px; white-space: nowrap; "><a href="http://www.amazon.com/TAG-Heuer-CAH1110-BA0850-Formula-Chronograph/product-reviews/B0019FP47E/ref=cm_cr_pr_hist_5?ie=UTF8&showViewpoints=0&filterBy=addFiveStar" style="font-family: verdana, arial, helvetica, sans-serif; color: rgb(0, 75, 145); ">5 star</a>:</td>
              <td width="60" align="left" class="tiny" title="56%" style="font-family: verdana, arial, helvetica, sans-serif; font-size: x-small; border-top-width: 0px; border-right-width: 0px; border-bottom-width: 0px; border-left-width: 0px; border-style: initial; border-color: initial; min-width: 60px; background-color: rgb(238, 238, 204); "><div style="background-color: rgb(255, 204, 102); height: 13px; width: 33px; "></div></td>
              <td align="right" class="tiny" style="font-family: verdana, arial, helvetica, sans-serif; font-size: x-small; border-top-width: 0px; border-right-width: 0px; border-bottom-width: 0px; border-left-width: 0px; border-style: initial; border-color: initial; "> (14)</td>
            </tr>
            <tr>
              <td align="left" class="tiny" style="font-family: verdana, arial, helvetica, sans-serif; font-size: x-small; border-top-width: 0px; border-right-width: 0px; border-bottom-width: 0px; border-left-width: 0px; border-style: initial; border-color: initial; padding-right: 0.5em; padding-bottom: 1px; white-space: nowrap; "><a href="http://www.amazon.com/TAG-Heuer-CAH1110-BA0850-Formula-Chronograph/product-reviews/B0019FP47E/ref=cm_cr_pr_hist_4?ie=UTF8&showViewpoints=0&filterBy=addFourStar" style="font-family: verdana, arial, helvetica, sans-serif; color: rgb(0, 75, 145); ">4 star</a>:</td>
              <td width="60" align="left" class="tiny" title="20%" style="font-family: verdana, arial, helvetica, sans-serif; font-size: x-small; border-top-width: 0px; border-right-width: 0px; border-bottom-width: 0px; border-left-width: 0px; border-style: initial; border-color: initial; min-width: 60px; background-color: rgb(238, 238, 204); "><div style="background-color: rgb(255, 204, 102); height: 13px; width: 12px; "></div></td>
              <td align="right" class="tiny" style="font-family: verdana, arial, helvetica, sans-serif; font-size: x-small; border-top-width: 0px; border-right-width: 0px; border-bottom-width: 0px; border-left-width: 0px; border-style: initial; border-color: initial; "> (5)</td>
            </tr>
            <tr>
              <td align="left" class="tiny" style="font-family: verdana, arial, helvetica, sans-serif; font-size: x-small; border-top-width: 0px; border-right-width: 0px; border-bottom-width: 0px; border-left-width: 0px; border-style: initial; border-color: initial; padding-right: 0.5em; padding-bottom: 1px; white-space: nowrap; "><span style="color:rgb(102, 102, 102); ">3 star</span>:</td>
              <td width="60" align="left" class="tiny" title="0%" style="font-family: verdana, arial, helvetica, sans-serif; font-size: x-small; border-top-width: 0px; border-right-width: 0px; border-bottom-width: 0px; border-left-width: 0px; border-style: initial; border-color: initial; background-color: rgb(238, 238, 204); "> </td>
              <td align="right" class="tiny" style="font-family: verdana, arial, helvetica, sans-serif; font-size: x-small; border-top-width: 0px; border-right-width: 0px; border-bottom-width: 0px; border-left-width: 0px; border-style: initial; border-color: initial; color: rgb(102, 102, 102); "> (0)</td>
            </tr>
            <tr>
              <td align="left" class="tiny" style="font-family: verdana, arial, helvetica, sans-serif; font-size: x-small; border-top-width: 0px; border-right-width: 0px; border-bottom-width: 0px; border-left-width: 0px; border-style: initial; border-color: initial; padding-right: 0.5em; padding-bottom: 1px; white-space: nowrap; "><span style="color:rgb(102, 102, 102); ">2 star</span>:</td>
              <td width="60" align="left" class="tiny" title="0%" style="font-family: verdana, arial, helvetica, sans-serif; font-size: x-small; border-top-width: 0px; border-right-width: 0px; border-bottom-width: 0px; border-left-width: 0px; border-style: initial; border-color: initial; background-color: rgb(238, 238, 204); "> </td>
              <td align="right" class="tiny" style="font-family: verdana, arial, helvetica, sans-serif; font-size: x-small; border-top-width: 0px; border-right-width: 0px; border-bottom-width: 0px; border-left-width: 0px; border-style: initial; border-color: initial; color: rgb(102, 102, 102); "> (0)</td>
            </tr>
            <tr>
              <td align="left" class="tiny" style="font-family: verdana, arial, helvetica, sans-serif; font-size: x-small; border-top-width: 0px; border-right-width: 0px; border-bottom-width: 0px; border-left-width: 0px; border-style: initial; border-color: initial; padding-right: 0.5em; padding-bottom: 1px; white-space: nowrap; "><a href="http://www.amazon.com/TAG-Heuer-CAH1110-BA0850-Formula-Chronograph/product-reviews/B0019FP47E/ref=cm_cr_pr_hist_1?ie=UTF8&showViewpoints=0&filterBy=addOneStar" style="font-family: verdana, arial, helvetica, sans-serif; color: rgb(0, 75, 145); ">1 star</a>:</td>
              <td width="60" align="left" class="tiny" title="24%" style="font-family: verdana, arial, helvetica, sans-serif; font-size: x-small; border-top-width: 0px; border-right-width: 0px; border-bottom-width: 0px; border-left-width: 0px; border-style: initial; border-color: initial; min-width: 60px; background-color: rgb(238, 238, 204); "><div style="background-color: rgb(255, 204, 102); height: 13px; width: 14px; "></div></td>
              <td align="right" class="tiny" style="font-family: verdana, arial, helvetica, sans-serif; font-size: x-small; border-top-width: 0px; border-right-width: 0px; border-bottom-width: 0px; border-left-width: 0px; border-style: initial; border-color: initial; "> (6)</td>
            </tr>
            <tr>
              <td style="font-family: verdana, arial, helvetica, sans-serif; font-size: small; border-top-width: 0px; border-right-width: 0px; border-bottom-width: 0px; border-left-width: 0px; border-style: initial; border-color: initial; "> </td>
              <td style="font-family: verdana, arial, helvetica, sans-serif; font-size: small; border-top-width: 0px; border-right-width: 0px; border-bottom-width: 0px; border-left-width: 0px; border-style: initial; border-color: initial; "><div style="width: 60px; "> </div></td>
              <td style="font-family: verdana, arial, helvetica, sans-serif; font-size: small; border-top-width: 0px; border-right-width: 0px; border-bottom-width: 0px; border-left-width: 0px; border-style: initial; border-color: initial; "> </td>
            </tr>
          </tbody>
        </table>
      </div></td>
      <td width="20" style="font-family: verdana, arial, helvetica, sans-serif; font-size: small; border-top-width: 0px; border-right-width: 0px; border-bottom-width: 0px; border-left-width: 0px; border-style: initial; border-color: initial; "><div style="width: 20px; "> </div>
      </td>
      <td valign="top" align="center" style="font-family: verdana, arial, helvetica, sans-serif; font-size: small; border-top-width: 0px; border-right-width: 0px; border-bottom-width: 0px; border-left-width: 0px; border-style: initial; border-color: initial; "><div class="tiny" align="left" style="font-family: verdana, arial, helvetica, sans-serif; font-size: x-small; ">
        <div><strong>Average Customer Review</strong></div>
        <div style="white-space: nowrap; "><span class="crAvgStars"><span class="asinReviewsSummary" name="B0019FP47E" ref="pr_all_summary_cm_cr_acr_pop_"><a href="http://www.amazon.com/TAG-Heuer-CAH1110-BA0850-Formula-Chronograph/product-reviews/B0019FP47E/ref=pr_all_summary_cm_cr_acr_img?ie=UTF8&showViewpoints=1" style="font-family: verdana, arial, helvetica, sans-serif; color: rgb(0, 75, 145); "><span class="swSprite s_star_4_0" title="3.8 out of 5 stars" style="display: inline-block; margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; position: relative; overflow-x: hidden; overflow-y: hidden; vertical-align: middle; background-image: url(http://g-ecx.images-amazon.com/images/G/01/common/sprites/sprite-site-wide-2._V181113497_.png); background-attachment: initial; background-origin: initial; background-clip: initial; background-color: initial; width: 65px; height: 13px; background-position: -43px 0px; background-repeat: no-repeat no-repeat; "><span style="position:absolute; left:-9999px; ">3.8 out of 5 stars</span></span></a> </span>(<a href="http://www.amazon.com/TAG-Heuer-CAH1110-BA0850-Formula-Chronograph/product-reviews/B0019FP47E/ref=pr_all_summary_cm_cr_acr_txt?ie=UTF8&showViewpoints=1" style="font-family: verdana, arial, helvetica, sans-serif; color: rgb(0, 75, 145); ">25 customer reviews</a>)</span></div>
        <div style="margin-top: 10px; ">
          <div style="margin-bottom: 5px; ">Share your thoughts with other customers</div>
          <a href="http://www.amazon.com/review/create-review/ref=cm_cr_pr_wr_but_top?ie=UTF8&nodeID=&asin=B0019FP47E" style="font-family: verdana, arial, helvetica, sans-serif; color: rgb(0, 75, 145); "><span class="cmtySprite s_createYourOwnReviewTan" style="display: inline-block; margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; position: relative; overflow-x: hidden; overflow-y: hidden; vertical-align: middle; background-image: xurl(http://g-ecx.images-amazon.com/images/G/01/common/sprites/sprite-communities._V197398854_.png); background-attachment: initial; background-origin: initial; background-clip: initial; background-color: initial; width: 145px; height: 22px; background-position: 0px -20px; background-repeat: no-repeat no-repeat; ">Create your own review</span></a></div>
      </div></td>
      <td style="font-family: verdana, arial, helvetica, sans-serif; font-size: small; border-top-width: 0px; border-right-width: 0px; border-bottom-width: 0px; border-left-width: 0px; border-style: initial; border-color: initial; "><div style="width: 20px; "> </div>
      </td>
      <td valign="top" align="right" style="font-family: verdana, arial, helvetica, sans-serif; font-size: small; border-top-width: 0px; border-right-width: 0px; border-bottom-width: 0px; border-left-width: 0px; border-style: initial; border-color: initial; "><form method="GET" action="http://www.amazon.com/gp/community-content-search/results/ref=cm_srch_q_rtr/" style="padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; ">
        <table border="0" cellpadding="0" cellspacing="0" width="250">
          <tbody>
            <tr>
              <td colspan="2" nowrap="nowrap" style="font-family: verdana, arial, helvetica, sans-serif; font-size: small; border-top-width: 0px; border-right-width: 0px; border-bottom-width: 0px; border-left-width: 0px; border-style: initial; border-color: initial; "><label for="search_rtr"><strong class="tiny" style="font-family: verdana, arial, helvetica, sans-serif; font-size: x-small; ">Search Customer Reviews</strong></label></td>
            </tr>
            <tr>
              <td style="font-family: verdana, arial, helvetica, sans-serif; font-size: small; border-top-width: 0px; border-right-width: 0px; border-bottom-width: 0px; border-left-width: 0px; border-style: initial; border-color: initial; width: 224px; "><input id="search_rtr" class="small" type="text" name="query" value="" widdit="on" autocomplete="off" style="font-family: verdana, arial, helvetica, sans-serif; font-size: small; width: 224px; "></td>
              <td style="font-family: verdana, arial, helvetica, sans-serif; font-size: small; border-top-width: 0px; border-right-width: 0px; border-bottom-width: 0px; border-left-width: 0px; border-style: initial; border-color: initial; padding-left: 5px; "><input type="image" title="Go" alt="Go" border="0" class="swSprite s_goTan" id="Go" value="" name="Go" src="http://g-ecx.images-amazon.com/images/G/01/x-locale/common/transparent-pixel._V192234675_.gif" style="display: inline-block; margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; position: relative; overflow-x: hidden; overflow-y: hidden; vertical-align: middle; background-image: url(http://g-ecx.images-amazon.com/images/G/01/common/sprites/sprite-site-wide-2._V181113497_.png); background-attachment: initial; background-origin: initial; background-clip: initial; background-color: initial; width: 21px; height: 21px; background-position: -50px -40px; background-repeat: no-repeat no-repeat; "></td>
            </tr>
            <tr>
              <td colspan="2" style="font-family: verdana, arial, helvetica, sans-serif; font-size: small; border-top-width: 0px; border-right-width: 0px; border-bottom-width: 0px; border-left-width: 0px; border-style: initial; border-color: initial; "><input type="checkbox" name="idx.asin" value="B0019FP47E" checked="">
                <span class="Apple-converted-space"> </span><span class="tiny" style="font-family: verdana, arial, helvetica, sans-serif; font-size: x-small; ">Only search this product's reviews</span></td>
            </tr>
          </tbody>
        </table>
      </form></td>
    </tr>
  </tbody>
</table>
<strong class="h3color" style="font-family: verdana, arial, helvetica, sans-serif; color: rgb(228, 121, 17); font-size: small; ">› </strong><a href="http://www.amazon.com/TAG-Heuer-CAH1110-BA0850-Formula-Chronograph/product-reviews/B0019FP47E/ref=cm_cr_pr_shwvpnt?ie=UTF8&showViewpoints=1&sortBy=bySubmissionDateDescending" style="font-family: verdana, arial, helvetica, sans-serif; color: rgb(0, 75, 145); "><strong>See most helpful viewpoints</strong></a><br>
<br>
<table class="CMheadingBar" border="0" cellpadding="0" cellspacing="0" width="100%" style="background-image: url(http://g-ecx.images-amazon.com/images/G/01/nav2/images/gui/tile-blue-bg._V46870869_.gif); background-attachment: initial; background-origin: initial; background-clip: initial; background-color: initial; border-top-width: 1px; border-top-style: solid; border-top-color: rgb(186, 218, 232); border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: rgb(186, 218, 232); padding-top: 6px; padding-right: 6px; padding-bottom: 6px; padding-left: 6px; background-position: initial initial; background-repeat: repeat no-repeat; ">
  <tbody>
    <tr>
      <td height="16" align="left" style="font-family: verdana, arial, helvetica, sans-serif; font-size: small; border-top-width: 0px; border-right-width: 0px; border-bottom-width: 0px; border-left-width: 0px; border-style: initial; border-color: initial; padding-left: 4px; padding-right: 4px; "><div class="CMpaginate" style="color: rgb(102, 102, 102); white-space: nowrap; "><span class="paging">‹ Previous |<span class="Apple-converted-space"> </span><span class="on" style="border-top-width: 1px; border-right-width: 1px; border-bottom-width: 1px; border-left-width: 1px; border-top-style: solid; border-right-style: solid; border-bottom-style: solid; border-left-style: solid; border-top-color: rgb(204, 102, 0); border-right-color: rgb(204, 102, 0); border-bottom-color: rgb(204, 102, 0); border-left-color: rgb(204, 102, 0); padding-top: 3px; padding-right: 3px; padding-bottom: 3px; padding-left: 3px; background-color: white; color: rgb(204, 102, 0); text-decoration: none; ">1</span><span class="Apple-converted-space"> </span><a href="http://www.amazon.com/TAG-Heuer-CAH1110-BA0850-Formula-Chronograph/product-reviews/B0019FP47E/ref=cm_cr_pr_top_link_2?ie=UTF8&showViewpoints=0&pageNumber=2" style="font-family: verdana, arial, helvetica, sans-serif; color: rgb(0, 75, 145); padding-top: 4px; padding-right: 4px; padding-bottom: 4px; padding-left: 4px; text-decoration: none; ">2</a><span class="Apple-converted-space"> </span><a href="http://www.amazon.com/TAG-Heuer-CAH1110-BA0850-Formula-Chronograph/product-reviews/B0019FP47E/ref=cm_cr_pr_top_link_3?ie=UTF8&showViewpoints=0&pageNumber=3" style="font-family: verdana, arial, helvetica, sans-serif; color: rgb(0, 75, 145); padding-top: 4px; padding-right: 4px; padding-bottom: 4px; padding-left: 4px; text-decoration: none; ">3</a><span class="Apple-converted-space"> </span>|<span class="Apple-converted-space"> </span><a href="http://www.amazon.com/TAG-Heuer-CAH1110-BA0850-Formula-Chronograph/product-reviews/B0019FP47E/ref=cm_cr_pr_top_link_next_2?ie=UTF8&showViewpoints=0&pageNumber=2" style="font-family: verdana, arial, helvetica, sans-serif; color: rgb(0, 75, 145); padding-top: 4px; padding-right: 4px; padding-bottom: 4px; padding-left: 4px; text-decoration: none; ">Next ›</a></span></div></td>
      <td height="16" align="right" style="font-family: verdana, arial, helvetica, sans-serif; font-size: small; border-top-width: 0px; border-right-width: 0px; border-bottom-width: 0px; border-left-width: 0px; border-style: initial; border-color: initial; padding-right: 4px; "><div class="" style="white-space: nowrap; "><strong class="on">Most Helpful First</strong><span class="Apple-converted-space"> </span>|<span class="Apple-converted-space"> </span><a href="http://www.amazon.com/TAG-Heuer-CAH1110-BA0850-Formula-Chronograph/product-reviews/B0019FP47E/ref=cm_cr_pr_top_recent?ie=UTF8&showViewpoints=0&sortBy=bySubmissionDateDescending" style="font-family: verdana, arial, helvetica, sans-serif; color: rgb(0, 75, 145); ">Newest First</a></div></td>
    </tr>
  </tbody>
</table>
<table id="productReviews" width="100%" cellspacing="0" cellpadding="0">
  <tbody>
    <tr>
      <td width="90%" style="font-family: verdana, arial, helvetica, sans-serif; font-size: small; border-top-width: 0px; border-right-width: 0px; border-bottom-width: 0px; border-left-width: 0px; border-style: initial; border-color: initial; "><a name="R2J3SMV6VPIZD2"></a><br>
        <div style="margin-left: 0.5em; ">
          <div style="margin-bottom: 0.5em; ">15 of 15 people found the following review helpful:</div>
          <div style="margin-bottom: 0.5em; "><span style="margin-right:5px; "><span class="swSprite s_star_4_0" title="4.0 out of 5 stars" style="display: inline-block; margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; position: relative; overflow-x: hidden; overflow-y: hidden; vertical-align: middle; background-image: url(http://g-ecx.images-amazon.com/images/G/01/common/sprites/sprite-site-wide-2._V181113497_.png); background-attachment: initial; background-origin: initial; background-clip: initial; background-color: initial; width: 65px; height: 13px; background-position: -43px 0px; background-repeat: no-repeat no-repeat; ">4.0 out of 5 stars</span><span class="Apple-converted-space"> </span></span><span style="vertical-align:middle; "><strong>Nice Classic Looking Watch</strong>,<span class="Apple-converted-space"> </span>March 17, 2010</span></div>
          <div style="margin-bottom: 0.5em; ">
            <div>
              <div style="float: left; ">By </div>
              <div style="float: left; "><a href="http://www.amazon.com/gp/pdp/profile/A39L35PUI58CFY/ref=cm_cr_pr_pdp" style="font-family: verdana, arial, helvetica, sans-serif; color: rgb(0, 75, 145); "><span style="font-weight:bold; ">Bubbles-Desmo "Danny Truong"</span></a><span class="Apple-converted-space"> </span>(Bay Area, CA)</div>
            </div>
            <div style="clear: both; "></div>
          </div>
          <div class="tiny" style="font-family: verdana, arial, helvetica, sans-serif; font-size: x-small; margin-bottom: 0.5em; "></div>
          <div class="tiny" style="font-family: verdana, arial, helvetica, sans-serif; font-size: x-small; margin-bottom: 0.5em; "><strong><span class="h3color tiny" style="font-family: verdana, arial, helvetica, sans-serif; color: rgb(228, 121, 17); font-size: x-small; ">This review is from:<span class="Apple-converted-space"> </span></span>TAG Heuer Men's CAH1110.BA0850 Formula 1 Chronograph Watch (Watch)</strong></div>
          I just purchased this watch through amazon.com. It was either this or the formula one alarm version at costco. The alarm feature on the other version isn't very useful so I decided against it. Packaging was nice, came in the tag box and case with manual. I like the look of chronograph watches and the additional feature to stopwatch anything is something i wanted to time rides, drives, runs etc...00
          <div style="padding-top: 10px; clear: both; width: 888px; ">
            <div style="float: left; padding-right: 15px; border-right-width: 1px; border-right-style: solid; border-right-color: rgb(204, 204, 204); ">
              <div style="padding-bottom: 5px; "><strong class="tiny" style="font-family: verdana, arial, helvetica, sans-serif; font-size: x-small; color: rgb(102, 102, 102); white-space: nowrap; ">Help other customers find the most helpful reviews</strong> </div>
              <div style="width: 300px; "><a name="R2J3SMV6VPIZD2.2115.Helpful.Reviews" style="font-size: 1px; "></a><span class="crVotingButtons"><span class="votingPrompt">Was this review helpful to you? </span><a rel="nofollow" class="votingButtonReviews" href="http://www.amazon.com/gp/voting/cast/Reviews/2115/R2J3SMV6VPIZD2/Helpful/1/ref=cm_cr_prvoteyn?ie=UTF8&token=7B7203D04B18D146B6ED3F430B2368A30D5C96FF&target=aHR0cDovL3d3dy5hbWF6b24uY29tL3Jldmlldy9CMDAxOUZQNDdFL3JlZj1jbV9jcl9wcnZvdGVyZHI_X2VuY29kaW5nPVVURjgmc2hvd1ZpZXdwb2ludHM9MA&voteAnchorName=R2J3SMV6VPIZD2.2115.Helpful.Reviews&voteSessionID=177-7238879-6529939" style="font-family: verdana, arial, helvetica, sans-serif; color: rgb(0, 75, 145); "><span class="cmtySprite s_largeYes" style="display: inline-block; margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; position: relative; overflow-x: hidden; overflow-y: hidden; vertical-align: middle; background-image: url(http://g-ecx.images-amazon.com/images/G/01/common/sprites/sprite-communities._V197398854_.png); background-attachment: initial; background-origin: initial; background-clip: initial; background-color: initial; width: 35px; height: 18px; background-position: 0px -670px; background-repeat: no-repeat no-repeat; ">Yes</span></a><span class="Apple-converted-space"> </span><a rel="nofollow" class="votingButtonReviews" href="http://www.amazon.com/gp/voting/cast/Reviews/2115/R2J3SMV6VPIZD2/Helpful/-1/ref=cm_cr_prvoteyn?ie=UTF8&token=50283AB35C8F5AC906EDFE07B298D44FEC8CBF6F&target=aHR0cDovL3d3dy5hbWF6b24uY29tL3Jldmlldy9CMDAxOUZQNDdFL3JlZj1jbV9jcl9wcnZvdGVyZHI_X2VuY29kaW5nPVVURjgmc2hvd1ZpZXdwb2ludHM9MA&voteAnchorName=R2J3SMV6VPIZD2.2115.Helpful.Reviews&voteSessionID=177-7238879-6529939" style="font-family: verdana, arial, helvetica, sans-serif; color: rgb(0, 75, 145); "><span class="cmtySprite s_largeNo" style="display: inline-block; margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; position: relative; overflow-x: hidden; overflow-y: hidden; vertical-align: middle; background-image: url(http://g-ecx.images-amazon.com/images/G/01/common/sprites/sprite-communities._V197398854_.png); background-attachment: initial; background-origin: initial; background-clip: initial; background-color: initial; width: 35px; height: 18px; background-position: -70px -670px; background-repeat: no-repeat no-repeat; ">No</span></a><span class="votingMessage"> </span></span></div>
            </div>
            <div style="float: left; ">
              <div style="padding-left: 15px; ">
                <div style="white-space: nowrap; "><span class="tiny" style="font-family: verdana, arial, helvetica, sans-serif; font-size: x-small; "><a name="R2J3SMV6VPIZD2.2115.Inappropriate.Reviews" style="font-size: 1px; "></a><span class="reportingButton"><a rel="nofollow" class="reportingButton" href="http://www.amazon.com/gp/voting/cast/Reviews/2115/R2J3SMV6VPIZD2/Inappropriate/1/ref=cm_cr_prvoteyn?ie=UTF8&token=D0FC13144AE84229D073883D256EC1D13F47167C&target=aHR0cDovL3d3dy5hbWF6b24uY29tL3Jldmlldy9CMDAxOUZQNDdFL3JlZj1jbV9jcl9wcnZvdGVyZHI_X2VuY29kaW5nPVVURjgmc2hvd1ZpZXdwb2ludHM9MA&voteAnchorName=R2J3SMV6VPIZD2.2115.Inappropriate.Reviews&voteSessionID=177-7238879-6529939" onclick="var w = window.open(this.href+'&type=popup','reportAbuse','height=380,width=580');w.focus();return false;" style="font-family: verdana, arial, helvetica, sans-serif; color: rgb(0, 75, 145); ">Report abuse</a></span><span class="Apple-converted-space"> </span></span><span style="color:rgb(204, 204, 204); ">|</span><span class="Apple-converted-space"> </span><span class="tiny" style="font-family: verdana, arial, helvetica, sans-serif; font-size: x-small; "><a href="http://www.amazon.com/review/R2J3SMV6VPIZD2/ref=cm_cr_pr_perm?ie=UTF8&ASIN=B0019FP47E&nodeID=&tag=&linkCode=" style="font-family: verdana, arial, helvetica, sans-serif; color: rgb(0, 75, 145); ">Permalink</a></span></div>
                <div style="white-space: nowrap; padding-top: 5px; "><a href="http://www.amazon.com/review/R2J3SMV6VPIZD2/ref=cm_cr_pr_cmt?ie=UTF8&ASIN=B0019FP47E&nodeID=&tag=&linkCode=#wasThisHelpful" style="font-family: verdana, arial, helvetica, sans-serif; color: rgb(0, 75, 145); "><span class="swSprite s_comment" style="display: inline-block; margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; position: relative; overflow-x: hidden; overflow-y: hidden; vertical-align: middle; background-image: url(http://g-ecx.images-amazon.com/images/G/01/common/sprites/sprite-site-wide-2._V181113497_.png); background-attachment: initial; background-origin: initial; background-clip: initial; background-color: initial; width: 16px; height: 15px; background-position: -80px -60px; background-repeat: no-repeat no-repeat; ">Comment</span></a> <a href="http://www.amazon.com/review/R2J3SMV6VPIZD2/ref=cm_cr_pr_cmt?ie=UTF8&ASIN=B0019FP47E&nodeID=&tag=&linkCode=#wasThisHelpful" style="font-family: verdana, arial, helvetica, sans-serif; color: rgb(0, 75, 145); ">Comment</a></div>
              </div>
            </div>
            <div style="clear: both; "></div>
          </div>
          <br>
        </div>
        <a name="R370G3C861M0KL"></a><br>
        <div style="margin-left: 0.5em; ">
          <div style="margin-bottom: 0.5em; ">24 of 28 people found the following review helpful:</div>
          <div style="margin-bottom: 0.5em; "><span class="swSprite s_star_1_0" title="1.0 out of 5 stars" style="display: inline-block; margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; position: relative; overflow-x: hidden; overflow-y: hidden; vertical-align: middle; background-image: url(http://g-ecx.images-amazon.com/images/G/01/common/sprites/sprite-site-wide-2._V181113497_.png); background-attachment: initial; background-origin: initial; background-clip: initial; background-color: initial; width: 65px; height: 13px; background-position: -82px 0px; background-repeat: no-repeat no-repeat; ">1.0 out of 5 stars</span><span class="Apple-converted-space"> </span><strong>Poor quality</strong>,<span class="Apple-converted-space"> </span>July 23, 2010</div>
          <div style="margin-bottom: 0.5em; ">
            <div>
              <div style="float: left; ">By </div>
              <div style="float: left; "><a href="http://www.amazon.com/gp/pdp/profile/ADEU9QI7OJT79/ref=cm_cr_pr_pdp" style="font-family: verdana, arial, helvetica, sans-serif; color: rgb(0, 75, 145); "><span style="font-weight:bold; ">Rohi</span></a><span class="Apple-converted-space"> </span>(USA)</div>
            </div>
            <div style="clear: both; "></div>
          </div>
          <div class="tiny" style="font-family: verdana, arial, helvetica, sans-serif; font-size: x-small; margin-bottom: 0.5em; "><strong><span class="h3color tiny" style="font-family: verdana, arial, helvetica, sans-serif; color: rgb(228, 121, 17); font-size: x-small; ">This review is from:<span class="Apple-converted-space"> </span></span>TAG Heuer Men's CAH1110.BA0850 Formula 1 Chronograph Watch (Watch)</strong></div>
          Bought watch at Longs Jewelers in Burlington MA. The stem (the part you wind up) has popped out three times. The first time, they fixed it under warranty. The second time, it was no longer under warranty, so Tag charged me $275. The watch came back and a week later the stem was gone again. I stuffed it in a drawer for a few months (angry) and when I finally got around to going back to the jeweler, Tag said me it would be another $275 as the warranty had expired. Shame on me for not bringing it back quicker but frankly I am sick of these guys. The jeweler (Long's Jeweler in Burlington Mass, useless and unhelpful) said warranty decisions from Tag are final.<br>
          <div style="padding-top: 10px; clear: both; width: 888px; ">
            <div style="float: left; padding-right: 15px; border-right-width: 1px; border-right-style: solid; border-right-color: rgb(204, 204, 204); ">
              <div style="padding-bottom: 5px; "><strong class="tiny" style="font-family: verdana, arial, helvetica, sans-serif; font-size: x-small; color: rgb(102, 102, 102); white-space: nowrap; ">Help other customers find the most helpful reviews</strong> </div>
              <div style="width: 300px; "><a name="R370G3C861M0KL.2115.Helpful.Reviews" style="font-size: 1px; "></a><span class="crVotingButtons"><span class="votingPrompt">Was this review helpful to you? </span><a rel="nofollow" class="votingButtonReviews" href="http://www.amazon.com/gp/voting/cast/Reviews/2115/R370G3C861M0KL/Helpful/1/ref=cm_cr_prvoteyn?ie=UTF8&token=C553A813418CD0A0506268FE43BA7DE78243DA13&target=aHR0cDovL3d3dy5hbWF6b24uY29tL3Jldmlldy9CMDAxOUZQNDdFL3JlZj1jbV9jcl9wcnZvdGVyZHI_X2VuY29kaW5nPVVURjgmc2hvd1ZpZXdwb2ludHM9MA&voteAnchorName=R370G3C861M0KL.2115.Helpful.Reviews&voteSessionID=177-7238879-6529939" style="font-family: verdana, arial, helvetica, sans-serif; color: rgb(0, 75, 145); "><span class="cmtySprite s_largeYes" style="display: inline-block; margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; position: relative; overflow-x: hidden; overflow-y: hidden; vertical-align: middle; background-image: url(http://g-ecx.images-amazon.com/images/G/01/common/sprites/sprite-communities._V197398854_.png); background-attachment: initial; background-origin: initial; background-clip: initial; background-color: initial; width: 35px; height: 18px; background-position: 0px -670px; background-repeat: no-repeat no-repeat; ">Yes</span></a><span class="Apple-converted-space"> </span><a rel="nofollow" class="votingButtonReviews" href="http://www.amazon.com/gp/voting/cast/Reviews/2115/R370G3C861M0KL/Helpful/-1/ref=cm_cr_prvoteyn?ie=UTF8&token=FDC99076E4FF63467062346AA703B5451964731F&target=aHR0cDovL3d3dy5hbWF6b24uY29tL3Jldmlldy9CMDAxOUZQNDdFL3JlZj1jbV9jcl9wcnZvdGVyZHI_X2VuY29kaW5nPVVURjgmc2hvd1ZpZXdwb2ludHM9MA&voteAnchorName=R370G3C861M0KL.2115.Helpful.Reviews&voteSessionID=177-7238879-6529939" style="font-family: verdana, arial, helvetica, sans-serif; color: rgb(0, 75, 145); "><span class="cmtySprite s_largeNo" style="display: inline-block; margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; position: relative; overflow-x: hidden; overflow-y: hidden; vertical-align: middle; background-image: url(http://g-ecx.images-amazon.com/images/G/01/common/sprites/sprite-communities._V197398854_.png); background-attachment: initial; background-origin: initial; background-clip: initial; background-color: initial; width: 35px; height: 18px; background-position: -70px -670px; background-repeat: no-repeat no-repeat; ">No</span></a><span class="votingMessage"> </span></span></div>
            </div>
            <div style="float: left; ">
              <div style="padding-left: 15px; ">
                <div style="white-space: nowrap; "><span class="tiny" style="font-family: verdana, arial, helvetica, sans-serif; font-size: x-small; "><a name="R370G3C861M0KL.2115.Inappropriate.Reviews" style="font-size: 1px; "></a><span class="reportingButton"><a rel="nofollow" class="reportingButton" href="http://www.amazon.com/gp/voting/cast/Reviews/2115/R370G3C861M0KL/Inappropriate/1/ref=cm_cr_prvoteyn?ie=UTF8&token=B70CB1FF56BE4710100A10151C322C7B20C6CB43&target=aHR0cDovL3d3dy5hbWF6b24uY29tL3Jldmlldy9CMDAxOUZQNDdFL3JlZj1jbV9jcl9wcnZvdGVyZHI_X2VuY29kaW5nPVVURjgmc2hvd1ZpZXdwb2ludHM9MA&voteAnchorName=R370G3C861M0KL.2115.Inappropriate.Reviews&voteSessionID=177-7238879-6529939" onclick="var w = window.open(this.href+'&type=popup','reportAbuse','height=380,width=580');w.focus();return false;" style="font-family: verdana, arial, helvetica, sans-serif; color: rgb(0, 75, 145); ">Report abuse</a></span><span class="Apple-converted-space"> </span></span><span style="color:rgb(204, 204, 204); ">|</span><span class="Apple-converted-space"> </span><span class="tiny" style="font-family: verdana, arial, helvetica, sans-serif; font-size: x-small; "><a href="http://www.amazon.com/review/R370G3C861M0KL/ref=cm_cr_pr_perm?ie=UTF8&ASIN=B0019FP47E&nodeID=&tag=&linkCode=" style="font-family: verdana, arial, helvetica, sans-serif; color: rgb(0, 75, 145); ">Permalink</a></span></div>
                <div style="white-space: nowrap; padding-top: 5px; "><a href="http://www.amazon.com/review/R370G3C861M0KL/ref=cm_cr_pr_cmt?ie=UTF8&ASIN=B0019FP47E&nodeID=&tag=&linkCode=#wasThisHelpful" style="font-family: verdana, arial, helvetica, sans-serif; color: rgb(0, 75, 145); "><span class="swSprite s_comment" style="display: inline-block; margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; position: relative; overflow-x: hidden; overflow-y: hidden; vertical-align: middle; background-image: url(http://g-ecx.images-amazon.com/images/G/01/common/sprites/sprite-site-wide-2._V181113497_.png); background-attachment: initial; background-origin: initial; background-clip: initial; background-color: initial; width: 16px; height: 15px; background-position: -80px -60px; background-repeat: no-repeat no-repeat; ">Comment</span></a> <a href="http://www.amazon.com/review/R370G3C861M0KL/ref=cm_cr_pr_cmt?ie=UTF8&ASIN=B0019FP47E&nodeID=&tag=&linkCode=#wasThisHelpful" style="font-family: verdana, arial, helvetica, sans-serif; color: rgb(0, 75, 145); ">Comments (4)</a></div>
              </div>
            </div>
            <div style="clear: both; "></div>
          </div>
          <br>
        </div>
        <a name="R3H4VXY99HIQA5"></a><br>
        <div style="margin-left: 0.5em; ">
          <div style="margin-bottom: 0.5em; ">5 of 5 people found the following review helpful:</div>
          <div style="margin-bottom: 0.5em; "><span class="swSprite s_star_5_0" title="5.0 out of 5 stars" style="display: inline-block; margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; position: relative; overflow-x: hidden; overflow-y: hidden; vertical-align: middle; background-image: url(http://g-ecx.images-amazon.com/images/G/01/common/sprites/sprite-site-wide-2._V181113497_.png); background-attachment: initial; background-origin: initial; background-clip: initial; background-color: initial; width: 65px; height: 13px; background-position: -30px 0px; background-repeat: no-repeat no-repeat; ">5.0 out of 5 stars</span><span class="Apple-converted-space"> </span><strong>Great Tag Heuer.</strong>,<span class="Apple-converted-space"> </span>February 4, 2010</div>
          <div style="margin-bottom: 0.5em; ">
            <div>
              <div style="float: left; ">By </div>
              <div style="float: left; "><a href="http://www.amazon.com/gp/pdp/profile/A3FWP38GD6VU1R/ref=cm_cr_pr_pdp" style="font-family: verdana, arial, helvetica, sans-serif; color: rgb(0, 75, 145); "><span style="font-weight:bold; ">M. Halus</span></a><span class="Apple-converted-space"> </span>(Santa Fe, New Mexico, US)<span class="Apple-converted-space"> </span>  </div>
            </div>
            <div style="clear: both; "></div>
          </div>
          <div class="tiny" style="font-family: verdana, arial, helvetica, sans-serif; font-size: x-small; margin-bottom: 0.5em; "></div>
          <div class="tiny" style="font-family: verdana, arial, helvetica, sans-serif; font-size: x-small; margin-bottom: 0.5em; "><strong><span class="h3color tiny" style="font-family: verdana, arial, helvetica, sans-serif; color: rgb(228, 121, 17); font-size: x-small; ">This review is from:<span class="Apple-converted-space"> </span></span>TAG Heuer Men's CAH1110.BA0850 Formula 1 Chronograph Watch (Watch)</strong></div>
          I was bit nervous about ordering a fine watch over the internet, but my fears were baseless. I love this watch. It is exactly what was advertised. The only downside is that since Amazon is not an official Tag Heuer retailer you don't get an official warranty card. However Amazon does provide a comparable 2 year warranty. All in all I am very pleased with my purchase.
          <div style="padding-top: 10px; clear: both; width: 888px; ">
            <div style="float: left; padding-right: 15px; border-right-width: 1px; border-right-style: solid; border-right-color: rgb(204, 204, 204); ">
              <div style="padding-bottom: 5px; "><strong class="tiny" style="font-family: verdana, arial, helvetica, sans-serif; font-size: x-small; color: rgb(102, 102, 102); white-space: nowrap; ">Help other customers find the most helpful reviews</strong> </div>
              <div style="width: 300px; "><a name="R3H4VXY99HIQA5.2115.Helpful.Reviews" style="font-size: 1px; "></a><span class="crVotingButtons"><span class="votingPrompt">Was this review helpful to you? </span><a rel="nofollow" class="votingButtonReviews" href="http://www.amazon.com/gp/voting/cast/Reviews/2115/R3H4VXY99HIQA5/Helpful/1/ref=cm_cr_prvoteyn?ie=UTF8&token=75C31467F71CE9790C94585B7F07440A6DCE8316&target=aHR0cDovL3d3dy5hbWF6b24uY29tL3Jldmlldy9CMDAxOUZQNDdFL3JlZj1jbV9jcl9wcnZvdGVyZHI_X2VuY29kaW5nPVVURjgmc2hvd1ZpZXdwb2ludHM9MA&voteAnchorName=R3H4VXY99HIQA5.2115.Helpful.Reviews&voteSessionID=177-7238879-6529939" style="font-family: verdana, arial, helvetica, sans-serif; color: rgb(0, 75, 145); "><span class="cmtySprite s_largeYes" style="display: inline-block; margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; position: relative; overflow-x: hidden; overflow-y: hidden; vertical-align: middle; background-image: url(http://g-ecx.images-amazon.com/images/G/01/common/sprites/sprite-communities._V197398854_.png); background-attachment: initial; background-origin: initial; background-clip: initial; background-color: initial; width: 35px; height: 18px; background-position: 0px -670px; background-repeat: no-repeat no-repeat; ">Yes</span></a><span class="Apple-converted-space"> </span><a rel="nofollow" class="votingButtonReviews" href="http://www.amazon.com/gp/voting/cast/Reviews/2115/R3H4VXY99HIQA5/Helpful/-1/ref=cm_cr_prvoteyn?ie=UTF8&token=09FDDA4588E0F546F36B5F9F3D55F9AFFBFB3C3F&target=aHR0cDovL3d3dy5hbWF6b24uY29tL3Jldmlldy9CMDAxOUZQNDdFL3JlZj1jbV9jcl9wcnZvdGVyZHI_X2VuY29kaW5nPVVURjgmc2hvd1ZpZXdwb2ludHM9MA&voteAnchorName=R3H4VXY99HIQA5.2115.Helpful.Reviews&voteSessionID=177-7238879-6529939" style="font-family: verdana, arial, helvetica, sans-serif; color: rgb(0, 75, 145); "><span class="cmtySprite s_largeNo" style="display: inline-block; margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; position: relative; overflow-x: hidden; overflow-y: hidden; vertical-align: middle; background-image: url(http://g-ecx.images-amazon.com/images/G/01/common/sprites/sprite-communities._V197398854_.png); background-attachment: initial; background-origin: initial; background-clip: initial; background-color: initial; width: 35px; height: 18px; background-position: -70px -670px; background-repeat: no-repeat no-repeat; ">No</span></a><span class="votingMessage"> </span></span></div>
            </div>
            <div style="float: left; ">
              <div style="padding-left: 15px; ">
                <div style="white-space: nowrap; "><span class="tiny" style="font-family: verdana, arial, helvetica, sans-serif; font-size: x-small; "><a name="R3H4VXY99HIQA5.2115.Inappropriate.Reviews" style="font-size: 1px; "></a><span class="reportingButton"><a rel="nofollow" class="reportingButton" href="http://www.amazon.com/gp/voting/cast/Reviews/2115/R3H4VXY99HIQA5/Inappropriate/1/ref=cm_cr_prvoteyn?ie=UTF8&token=A725DDF057673E379199668E580B912BD52B4297&target=aHR0cDovL3d3dy5hbWF6b24uY29tL3Jldmlldy9CMDAxOUZQNDdFL3JlZj1jbV9jcl9wcnZvdGVyZHI_X2VuY29kaW5nPVVURjgmc2hvd1ZpZXdwb2ludHM9MA&voteAnchorName=R3H4VXY99HIQA5.2115.Inappropriate.Reviews&voteSessionID=177-7238879-6529939" onclick="var w = window.open(this.href+'&type=popup','reportAbuse','height=380,width=580');w.focus();return false;" style="font-family: verdana, arial, helvetica, sans-serif; color: rgb(0, 75, 145); ">Report abuse</a></span><span class="Apple-converted-space"> </span></span><span style="color:rgb(204, 204, 204); ">|</span><span class="Apple-converted-space"> </span><span class="tiny" style="font-family: verdana, arial, helvetica, sans-serif; font-size: x-small; "><a href="http://www.amazon.com/review/R3H4VXY99HIQA5/ref=cm_cr_pr_perm?ie=UTF8&ASIN=B0019FP47E&nodeID=&tag=&linkCode=" style="font-family: verdana, arial, helvetica, sans-serif; color: rgb(0, 75, 145); ">Permalink</a></span></div>
                <div style="white-space: nowrap; padding-top: 5px; "><a href="http://www.amazon.com/review/R3H4VXY99HIQA5/ref=cm_cr_pr_cmt?ie=UTF8&ASIN=B0019FP47E&nodeID=&tag=&linkCode=#wasThisHelpful" style="font-family: verdana, arial, helvetica, sans-serif; color: rgb(0, 75, 145); "><span class="swSprite s_comment" style="display: inline-block; margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; position: relative; overflow-x: hidden; overflow-y: hidden; vertical-align: middle; background-image: url(http://g-ecx.images-amazon.com/images/G/01/common/sprites/sprite-site-wide-2._V181113497_.png); background-attachment: initial; background-origin: initial; background-clip: initial; background-color: initial; width: 16px; height: 15px; background-position: -80px -60px; background-repeat: no-repeat no-repeat; ">Comment</span></a> <a href="http://www.amazon.com/review/R3H4VXY99HIQA5/ref=cm_cr_pr_cmt?ie=UTF8&ASIN=B0019FP47E&nodeID=&tag=&linkCode=#wasThisHelpful" style="font-family: verdana, arial, helvetica, sans-serif; color: rgb(0, 75, 145); ">Comment</a></div>
              </div>
            </div>
            <div style="clear: both; "></div>
          </div>
          <br>
        </div>
        <a name="R29PWXMR5D3PS2"></a><br>
        <div style="margin-left: 0.5em; ">
          <div style="margin-bottom: 0.5em; ">6 of 7 people found the following review helpful:</div>
          <div style="margin-bottom: 0.5em; "><span class="swSprite s_star_5_0" title="5.0 out of 5 stars" style="display: inline-block; margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; position: relative; overflow-x: hidden; overflow-y: hidden; vertical-align: middle; background-image: url(http://g-ecx.images-amazon.com/images/G/01/common/sprites/sprite-site-wide-2._V181113497_.png); background-attachment: initial; background-origin: initial; background-clip: initial; background-color: initial; width: 65px; height: 13px; background-position: -30px 0px; background-repeat: no-repeat no-repeat; ">5.0 out of 5 stars</span><span class="Apple-converted-space"> </span><strong>Beautiful Watch... Great Price... Brand Name... The Trifecta!</strong>,<span class="Apple-converted-space"> </span>January 11, 2009</div>
          <div style="margin-bottom: 0.5em; ">
            <div>
              <div style="float: left; ">By </div>
              <div style="float: left; "><a href="http://www.amazon.com/gp/pdp/profile/A2MK7OAT029AMI/ref=cm_cr_pr_pdp" style="font-family: verdana, arial, helvetica, sans-serif; color: rgb(0, 75, 145); "><span style="font-weight:bold; ">Joseph R. Laroza "RJ Laroza"</span></a><span class="Apple-converted-space"> </span>(marina del rey, california) -<span class="Apple-converted-space"> </span><a href="http://www.amazon.com/gp/cdp/member-reviews/A2MK7OAT029AMI/ref=cm_cr_pr_auth_rev?ie=UTF8&sort_by=MostRecentReview" style="font-family: verdana, arial, helvetica, sans-serif; color: rgb(0, 75, 145); ">See all my reviews</a><span class="Apple-converted-space"> </span>  </div>
            </div>
            <div style="clear: both; "></div>
          </div>
          <div class="tiny" style="font-family: verdana, arial, helvetica, sans-serif; font-size: x-small; margin-bottom: 0.5em; "><strong><span class="h3color tiny" style="font-family: verdana, arial, helvetica, sans-serif; color: rgb(228, 121, 17); font-size: x-small; ">This review is from:<span class="Apple-converted-space"> </span></span>TAG Heuer Men's CAH1110.BA0850 Formula 1 Chronograph Watch (Watch)</strong></div>
          This was my first Tag Heuer. It's one of the most beautiful watches I own... my other two watches are a Movado Luno and a Kenneth Cole dress watch. Everything works as its supposed to, with incredibly accurate time keeping.
          <div style="padding-top: 10px; clear: both; width: 888px; ">
            <div style="float: left; padding-right: 15px; border-right-width: 1px; border-right-style: solid; border-right-color: rgb(204, 204, 204); ">
              <div style="padding-bottom: 5px; "><strong class="tiny" style="font-family: verdana, arial, helvetica, sans-serif; font-size: x-small; color: rgb(102, 102, 102); white-space: nowrap; ">Help other customers find the most helpful reviews</strong> </div>
              <div style="width: 300px; "><a name="R29PWXMR5D3PS2.2115.Helpful.Reviews" style="font-size: 1px; "></a><span class="crVotingButtons"><span class="votingPrompt">Was this review helpful to you? </span><a rel="nofollow" class="votingButtonReviews" href="http://www.amazon.com/gp/voting/cast/Reviews/2115/R29PWXMR5D3PS2/Helpful/1/ref=cm_cr_prvoteyn?ie=UTF8&token=81AF2C2E645D3B118C4F04978F7063DBC3A79F58&target=aHR0cDovL3d3dy5hbWF6b24uY29tL3Jldmlldy9CMDAxOUZQNDdFL3JlZj1jbV9jcl9wcnZvdGVyZHI_X2VuY29kaW5nPVVURjgmc2hvd1ZpZXdwb2ludHM9MA&voteAnchorName=R29PWXMR5D3PS2.2115.Helpful.Reviews&voteSessionID=177-7238879-6529939" style="font-family: verdana, arial, helvetica, sans-serif; color: rgb(0, 75, 145); "><span class="cmtySprite s_largeYes" style="display: inline-block; margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; position: relative; overflow-x: hidden; overflow-y: hidden; vertical-align: middle; background-image: url(http://g-ecx.images-amazon.com/images/G/01/common/sprites/sprite-communities._V197398854_.png); background-attachment: initial; background-origin: initial; background-clip: initial; background-color: initial; width: 35px; height: 18px; background-position: 0px -670px; background-repeat: no-repeat no-repeat; ">Yes</span></a><span class="Apple-converted-space"> </span><a rel="nofollow" class="votingButtonReviews" href="http://www.amazon.com/gp/voting/cast/Reviews/2115/R29PWXMR5D3PS2/Helpful/-1/ref=cm_cr_prvoteyn?ie=UTF8&token=4BB9345F209BDDC5C1B997D3BA43C566C4B3BD95&target=aHR0cDovL3d3dy5hbWF6b24uY29tL3Jldmlldy9CMDAxOUZQNDdFL3JlZj1jbV9jcl9wcnZvdGVyZHI_X2VuY29kaW5nPVVURjgmc2hvd1ZpZXdwb2ludHM9MA&voteAnchorName=R29PWXMR5D3PS2.2115.Helpful.Reviews&voteSessionID=177-7238879-6529939" style="font-family: verdana, arial, helvetica, sans-serif; color: rgb(0, 75, 145); "><span class="cmtySprite s_largeNo" style="display: inline-block; margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; position: relative; overflow-x: hidden; overflow-y: hidden; vertical-align: middle; background-image: url(http://g-ecx.images-amazon.com/images/G/01/common/sprites/sprite-communities._V197398854_.png); background-attachment: initial; background-origin: initial; background-clip: initial; background-color: initial; width: 35px; height: 18px; background-position: -70px -670px; background-repeat: no-repeat no-repeat; ">No</span></a><span class="votingMessage"> </span></span></div>
            </div>
            <div style="float: left; ">
              <div style="padding-left: 15px; ">
                <div style="white-space: nowrap; "><span class="tiny" style="font-family: verdana, arial, helvetica, sans-serif; font-size: x-small; "><a name="R29PWXMR5D3PS2.2115.Inappropriate.Reviews" style="font-size: 1px; "></a><span class="reportingButton"><a rel="nofollow" class="reportingButton" href="http://www.amazon.com/gp/voting/cast/Reviews/2115/R29PWXMR5D3PS2/Inappropriate/1/ref=cm_cr_prvoteyn?ie=UTF8&token=2FA56D5902FBDEDFCEB9342666BB0D1F1A497CAA&target=aHR0cDovL3d3dy5hbWF6b24uY29tL3Jldmlldy9CMDAxOUZQNDdFL3JlZj1jbV9jcl9wcnZvdGVyZHI_X2VuY29kaW5nPVVURjgmc2hvd1ZpZXdwb2ludHM9MA&voteAnchorName=R29PWXMR5D3PS2.2115.Inappropriate.Reviews&voteSessionID=177-7238879-6529939" onclick="var w = window.open(this.href+'&type=popup','reportAbuse','height=380,width=580');w.focus();return false;" style="font-family: verdana, arial, helvetica, sans-serif; color: rgb(0, 75, 145); ">Report abuse</a></span><span class="Apple-converted-space"> </span></span><span style="color:rgb(204, 204, 204); ">|</span><span class="Apple-converted-space"> </span><span class="tiny" style="font-family: verdana, arial, helvetica, sans-serif; font-size: x-small; "><a href="http://www.amazon.com/review/R29PWXMR5D3PS2/ref=cm_cr_pr_perm?ie=UTF8&ASIN=B0019FP47E&nodeID=&tag=&linkCode=" style="font-family: verdana, arial, helvetica, sans-serif; color: rgb(0, 75, 145); ">Permalink</a></span></div>
                <div style="white-space: nowrap; padding-top: 5px; "><a href="http://www.amazon.com/review/R29PWXMR5D3PS2/ref=cm_cr_pr_cmt?ie=UTF8&ASIN=B0019FP47E&nodeID=&tag=&linkCode=#wasThisHelpful" style="font-family: verdana, arial, helvetica, sans-serif; color: rgb(0, 75, 145); "><span class="swSprite s_comment" style="display: inline-block; margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; position: relative; overflow-x: hidden; overflow-y: hidden; vertical-align: middle; background-image: url(http://g-ecx.images-amazon.com/images/G/01/common/sprites/sprite-site-wide-2._V181113497_.png); background-attachment: initial; background-origin: initial; background-clip: initial; background-color: initial; width: 16px; height: 15px; background-position: -80px -60px; background-repeat: no-repeat no-repeat; ">Comment</span></a> <a href="http://www.amazon.com/review/R29PWXMR5D3PS2/ref=cm_cr_pr_cmt?ie=UTF8&ASIN=B0019FP47E&nodeID=&tag=&linkCode=#wasThisHelpful" style="font-family: verdana, arial, helvetica, sans-serif; color: rgb(0, 75, 145); ">Comment</a></div>
              </div>
            </div>
            <div style="clear: both; "><br>
        </div>
          </div>
        </div>
        <a name="R1GWIM9ES3X0LN"></a><br>
        <div style="margin-left: 0.5em; ">
          <div style="margin-bottom: 0.5em; "></div>
        </div></td>
    </tr>
  </tbody>
</table>
</span>
</body>
</html>
