package com.bpd.employee.vos;
// Generated Sep 3, 2010 10:39:15 AM by Hibernate Tools 3.2.1.GA

/**
 * AsOfEmployee generated by hbm2java
 */
public class EmployeePositionVO {

    public Integer codigo_empleado;
    public String nombre_empleado;
    public String fecha_efectividad_inicial;
    public String fecha_efectividad_final;
    public Integer anos_en_puesto;
    public Integer meses_en_puesto;
    public Integer dias_en_puesto;
    public String cargo;
    public String dependencia;
    public String empresa;
    public String tiempo_en_el_puesto;
}
