package com.bpd.hipos.pojos;
// Generated May 19, 2011 7:38:40 PM by Hibernate Tools 3.2.1.GA



/**
 * HiposTarifarioSeguroMedicoInternacional generated by hbm2java
 */
public class HiposTarifarioSeguroMedicoInternacional  implements java.io.Serializable {


     private Integer id;
     private int minAge;
     private int maxAge;
     private String type;
     private Double ammountM;
     private Double ammountF;
     private String status;

    public HiposTarifarioSeguroMedicoInternacional() {
    }

	
    public HiposTarifarioSeguroMedicoInternacional(int minAge, int maxAge, String type, String status) {
        this.minAge = minAge;
        this.maxAge = maxAge;
        this.type = type;
        this.status = status;
    }
    public HiposTarifarioSeguroMedicoInternacional(int minAge, int maxAge, String type, Double ammountM, Double ammountF, String status) {
       this.minAge = minAge;
       this.maxAge = maxAge;
       this.type = type;
       this.ammountM = ammountM;
       this.ammountF = ammountF;
       this.status = status;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getMinAge() {
        return this.minAge;
    }
    
    public void setMinAge(int minAge) {
        this.minAge = minAge;
    }
    public int getMaxAge() {
        return this.maxAge;
    }
    
    public void setMaxAge(int maxAge) {
        this.maxAge = maxAge;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public Double getAmmountM() {
        return this.ammountM;
    }
    
    public void setAmmountM(Double ammountM) {
        this.ammountM = ammountM;
    }
    public Double getAmmountF() {
        return this.ammountF;
    }
    
    public void setAmmountF(Double ammountF) {
        this.ammountF = ammountF;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


