package com.bpd.hipos.pojos;
// Generated May 19, 2011 7:38:40 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;

/**
 * HiposAsignaciones generated by hbm2java
 */
public class HiposAsignaciones implements java.io.Serializable {

    private Integer id;
    private String codigoEmpleado;
    private Integer idEntidad;
    private int idActividad;
    private String nombreActividadAdhoc;
    private Date fechaInicial;
    private Date fechaFinal;
    private Integer estado;
    private Date fechaRegistro;
    private String logonUser;

    public HiposAsignaciones() {
    }

    public HiposAsignaciones(String codigoEmpleado, int idActividad, Date fechaInicial, Date fechaFinal, String logonUser) {
        this.codigoEmpleado = codigoEmpleado;
        this.idActividad = idActividad;
        this.fechaInicial = fechaInicial;
        this.fechaFinal = fechaFinal;
        this.logonUser = logonUser;
    }

    public HiposAsignaciones(String codigoEmpleado, Integer idEntidad, int idActividad, String nombreActividadAdhoc, Date fechaInicial, Date fechaFinal, Integer estado, Date fechaRegistro, String logonUser) {
        this.codigoEmpleado = codigoEmpleado;
        this.idEntidad = idEntidad;
        this.idActividad = idActividad;
        this.nombreActividadAdhoc = nombreActividadAdhoc;
        this.fechaInicial = fechaInicial;
        this.fechaFinal = fechaFinal;
        this.estado = estado;
        this.fechaRegistro = fechaRegistro;
        this.logonUser = logonUser;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getCodigoEmpleado() {
        return this.codigoEmpleado;
    }

    public void setCodigoEmpleado(String codigoEmpleado) {
        this.codigoEmpleado = codigoEmpleado;
    }

    public Integer getIdEntidad() {
        return this.idEntidad;
    }

    public void setIdEntidad(Integer idEntidad) {
        this.idEntidad = idEntidad;
    }

    public int getIdActividad() {
        return this.idActividad;
    }

    public void setIdActividad(int idActividad) {
        this.idActividad = idActividad;
    }

    public String getNombreActividadAdhoc() {
        return this.nombreActividadAdhoc;
    }

    public void setNombreActividadAdhoc(String nombreActividadAdhoc) {
        this.nombreActividadAdhoc = nombreActividadAdhoc;
    }

    public Date getFechaInicial() {
        return this.fechaInicial;
    }

    public void setFechaInicial(Date fechaInicial) {
        this.fechaInicial = fechaInicial;
    }

    public Date getFechaFinal() {
        return this.fechaFinal;
    }

    public void setFechaFinal(Date fechaFinal) {
        this.fechaFinal = fechaFinal;
    }

    public Integer getEstado() {
        return this.estado;
    }

    public void setEstado(Integer estado) {
        this.estado = estado;
    }

    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }

    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }

    public String getLogonUser() {
        return this.logonUser;
    }

    public void setLogonUser(String logonUser) {
        this.logonUser = logonUser;
    }
}
