package com.bpd.hipos.pojos;
// Generated May 19, 2011 7:38:40 PM by Hibernate Tools 3.2.1.GA



/**
 * HiposDependientes generated by hbm2java
 */
public class HiposDependientes  implements java.io.Serializable {


     private Integer id;
     private String codigoEmpleado;
     private String parentesco;
     private Integer edad;
     private Double percent;
     private Double ammount;

    public HiposDependientes() {
    }

	
    public HiposDependientes(String codigoEmpleado) {
        this.codigoEmpleado = codigoEmpleado;
    }
    public HiposDependientes(String codigoEmpleado, String parentesco, Integer edad, Double percent, Double ammount) {
       this.codigoEmpleado = codigoEmpleado;
       this.parentesco = parentesco;
       this.edad = edad;
       this.percent = percent;
       this.ammount = ammount;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getCodigoEmpleado() {
        return this.codigoEmpleado;
    }
    
    public void setCodigoEmpleado(String codigoEmpleado) {
        this.codigoEmpleado = codigoEmpleado;
    }
    public String getParentesco() {
        return this.parentesco;
    }
    
    public void setParentesco(String parentesco) {
        this.parentesco = parentesco;
    }
    public Integer getEdad() {
        return this.edad;
    }
    
    public void setEdad(Integer edad) {
        this.edad = edad;
    }
    public Double getPercent() {
        return this.percent;
    }
    
    public void setPercent(Double percent) {
        this.percent = percent;
    }
    public Double getAmmount() {
        return this.ammount;
    }
    
    public void setAmmount(Double ammount) {
        this.ammount = ammount;
    }




}


