package com.bpd.hipos.pojos;
// Generated May 19, 2011 7:38:40 PM by Hibernate Tools 3.2.1.GA

/**
 * HipoActividades generated by hbm2java
 */
public class HipoActividades implements java.io.Serializable {

    private Integer id;
    private String name;
    private Integer idEntity;
    private Integer idType;
    private String status;

    public HipoActividades() {
    }

    public HipoActividades(String name, Integer idEntity, Integer idType, String status) {
        this.name = name;
        this.idEntity = idEntity;
        this.idType = idType;
        this.status = status;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getIdEntity() {
        return this.idEntity;
    }

    public void setIdEntity(Integer idEntity) {
        this.idEntity = idEntity;
    }

    public Integer getIdType() {
        return this.idType;
    }

    public void setIdType(Integer idType) {
        this.idType = idType;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }
}
